# Этот предмет кладём в камнерез, и он же является основным
# (первым из одного или двух) ингредиентом любой шапки
default-ingredient: CARVED_PUMPKIN

# Этот предмет получаем на выходе камнереза в качестве
# кнопки входа в меню создания шапок
store-open-menu-item:
  material: CARVED_PUMPKIN
  displayname: "<yellow>Открыть меню создания шапок"
  custom-model-data: 60